### ISSUE TITLE
What about signals that have no type ?

### ISSUE THREAD

**Issue by ramasauskas** [jheiling/unity-signals#2]
To be more concrete, I'm talking about such Signal that is an empty game event just for notifying.

**Comment by jheiling** [comment]
I didn't include that because it would be just a wrapper around an UnityEvent with no additional functionality. Or am I missing something?

So I would use either just a ScriptableObject with an UnityEvent, or a FloatSignal and set it's Value to the current time to trigger the OnChanged event.

**Comment by ramasauskas** [comment]
True, that makes sense. I thought there is some kind of additional functionality by providing the user an additional EmptySignalListener which handles the subscription logic, description providers and such.

Of course anyone can code this in into their app, but I feel I'd be more convenient if the plugin offered this :)

Also I'm curious if you tried creating some kind of class that can store multiple listeners to different that type of signal, instead of adding the same component over and over, cluttering the component view. I'm not sure if this is possible generic wise (especially the way Unity treats generics).

**Comment by jheiling** [comment]
Good point. I will implement an EmptySignal asap...

Re multiple listeners in one class: because Unity can't serialize generics you need one listener class for each combination of signals you want to observe. If you don't want to write a class for that you could just put all the listeners in a separate GameObject.

**Comment by jheiling** [comment]
Implemented
